/*
 * generated by Xtext 2.25.0
 */
package org.mosig.mde.graphdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.mosig.mde.graphdsl.GraphRuntimeModule;
import org.mosig.mde.graphdsl.GraphStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GraphIdeSetup extends GraphStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GraphRuntimeModule(), new GraphIdeModule()));
	}
	
}
