/*
 * generated by Xtext 2.25.0
 */
package mosig.asmae.acceleo.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractFormValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(mosig.asmae.acceleo.form.FormPackage.eINSTANCE);
		return result;
	}
}
