/*
 * generated by Xtext 2.25.0
 */
package org.mosig.mde.graphdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGraphScopeProvider extends DelegatingScopeProvider {
}
