/*
 * generated by Xtext 2.25.0
 */
package xtext.tutorial.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.tutorial.parser.antlr.internal.InternalAIRParser;
import xtext.tutorial.services.AIRGrammarAccess;

public class AIRParser extends AbstractAntlrParser {

	@Inject
	private AIRGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAIRParser createParser(XtextTokenStream stream) {
		return new InternalAIRParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public AIRGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AIRGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
