##################################################
# Default makefile
# Redirect make to target makefile
##################################################

all:
	make -f MakefileCrossRoad.mk all
clean:
	make -f MakefileCrossRoad.mk clean
.PHONY: 
	make -f MakefileCrossRoad.mk all clean
