/*
 * generated by Xtext 2.25.0
 */
package org.mosig.lab4.myfamily.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.mosig.lab4.myfamily.ui.internal.MyfamilyActivator;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FamilyExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MyfamilyActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MyfamilyActivator activator = MyfamilyActivator.getInstance();
		return activator != null ? activator.getInjector(MyfamilyActivator.ORG_MOSIG_LAB4_MYFAMILY_FAMILY) : null;
	}

}
