/*
 * generated by Xtext 2.25.0
 */
package asmae.ocl.family.parser.antlr;

import asmae.ocl.family.parser.antlr.internal.InternalFamilyParser;
import asmae.ocl.family.services.FamilyGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class FamilyParser extends AbstractAntlrParser {

	@Inject
	private FamilyGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFamilyParser createParser(XtextTokenStream stream) {
		return new InternalFamilyParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "FamilyModel";
	}

	public FamilyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FamilyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
