/*
 * generated by Xtext 2.25.0
 */
package asmae.form;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FormStandaloneSetup extends FormStandaloneSetupGenerated {

	public static void doSetup() {
		new FormStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
