grammar asmae.form.Form with org.eclipse.xtext.common.Terminals

generate form "http://www.form.asmae/Form"

Model :
	'Questionnaire' name=STRING (lesQuestions+=Question)* ;
	
Question :
	'Question' label=STRING kindOf=Kind;
	
Kind : input | choice | option ;

input : name=ID ;

choice : name=ID (lesChoix+=check)+;

check : "[]" label=STRING name=ID;

option : name=ID (lesOptions+=radio)+;

radio: "()" label=STRING name=ID;
