/*
 * generated by Xtext 2.25.0
 */
package mosig.asmae.acceleo.ui.tests;

import com.google.inject.Injector;
import mosig.asmae.form.ui.internal.FormActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class FormUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FormActivator.getInstance().getInjector("mosig.asmae.acceleo.Form");
	}

}
