/**
 * generated by Xtext 2.25.0
 */
package org.mosig.lab4.myfamily.family;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mosig.lab4.myfamily.family.Model#getFamilies <em>Families</em>}</li>
 * </ul>
 *
 * @see org.mosig.lab4.myfamily.family.FamilyPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Families</b></em>' containment reference list.
   * The list contents are of type {@link org.mosig.lab4.myfamily.family.Family}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Families</em>' containment reference list.
   * @see org.mosig.lab4.myfamily.family.FamilyPackage#getModel_Families()
   * @model containment="true"
   * @generated
   */
  EList<Family> getFamilies();

} // Model
