/*
 * generated by Xtext 2.25.0
 */
package asmae.ocl.family.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFamilyScopeProvider extends DelegatingScopeProvider {
}
