/*
 * generated by Xtext 2.25.0
 */
package org.mosig.lab4.myfamily.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.mosig.lab4.myfamily.ui.internal.MyfamilyActivator;

public class FamilyUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MyfamilyActivator.getInstance().getInjector("org.mosig.lab4.myfamily.Family");
	}

}
