/**
 * generated by Xtext 2.25.0
 */
package asmae.ocl.family.family;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link asmae.ocl.family.family.FamilyModel#getFamilies <em>Families</em>}</li>
 * </ul>
 *
 * @see asmae.ocl.family.family.FamilyPackage#getFamilyModel()
 * @model
 * @generated
 */
public interface FamilyModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Families</b></em>' containment reference list.
   * The list contents are of type {@link asmae.ocl.family.family.Family}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Families</em>' containment reference list.
   * @see asmae.ocl.family.family.FamilyPackage#getFamilyModel_Families()
   * @model containment="true"
   * @generated
   */
  EList<Family> getFamilies();

} // FamilyModel
