/**
 * generated by Xtext 2.25.0
 */
package asmae.ocl.family.family;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Family</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link asmae.ocl.family.family.Family#getLastName <em>Last Name</em>}</li>
 *   <li>{@link asmae.ocl.family.family.Family#getFather <em>Father</em>}</li>
 *   <li>{@link asmae.ocl.family.family.Family#getMother <em>Mother</em>}</li>
 *   <li>{@link asmae.ocl.family.family.Family#getSons <em>Sons</em>}</li>
 *   <li>{@link asmae.ocl.family.family.Family#getDaughters <em>Daughters</em>}</li>
 * </ul>
 *
 * @see asmae.ocl.family.family.FamilyPackage#getFamily()
 * @model
 * @generated
 */
public interface Family extends EObject
{
  /**
   * Returns the value of the '<em><b>Last Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Last Name</em>' attribute.
   * @see #setLastName(String)
   * @see asmae.ocl.family.family.FamilyPackage#getFamily_LastName()
   * @model
   * @generated
   */
  String getLastName();

  /**
   * Sets the value of the '{@link asmae.ocl.family.family.Family#getLastName <em>Last Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Last Name</em>' attribute.
   * @see #getLastName()
   * @generated
   */
  void setLastName(String value);

  /**
   * Returns the value of the '<em><b>Father</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Father</em>' reference.
   * @see #setFather(Member)
   * @see asmae.ocl.family.family.FamilyPackage#getFamily_Father()
   * @model
   * @generated
   */
  Member getFather();

  /**
   * Sets the value of the '{@link asmae.ocl.family.family.Family#getFather <em>Father</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Father</em>' reference.
   * @see #getFather()
   * @generated
   */
  void setFather(Member value);

  /**
   * Returns the value of the '<em><b>Mother</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mother</em>' reference.
   * @see #setMother(Member)
   * @see asmae.ocl.family.family.FamilyPackage#getFamily_Mother()
   * @model
   * @generated
   */
  Member getMother();

  /**
   * Sets the value of the '{@link asmae.ocl.family.family.Family#getMother <em>Mother</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mother</em>' reference.
   * @see #getMother()
   * @generated
   */
  void setMother(Member value);

  /**
   * Returns the value of the '<em><b>Sons</b></em>' containment reference list.
   * The list contents are of type {@link asmae.ocl.family.family.Member}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sons</em>' containment reference list.
   * @see asmae.ocl.family.family.FamilyPackage#getFamily_Sons()
   * @model containment="true"
   * @generated
   */
  EList<Member> getSons();

  /**
   * Returns the value of the '<em><b>Daughters</b></em>' containment reference list.
   * The list contents are of type {@link asmae.ocl.family.family.Member}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Daughters</em>' containment reference list.
   * @see asmae.ocl.family.family.FamilyPackage#getFamily_Daughters()
   * @model containment="true"
   * @generated
   */
  EList<Member> getDaughters();

} // Family
