/*
 * generated by Xtext 2.25.0
 */
package org.mosig.lab4.myfamily.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FamilyAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/mosig/lab4/myfamily/parser/antlr/internal/InternalFamily.tokens");
	}
}
