/**
 * generated by Xtext 2.25.0
 */
package mosig.asmae.acceleo.form.impl;

import java.util.Collection;

import mosig.asmae.acceleo.form.FormPackage;
import mosig.asmae.acceleo.form.option;
import mosig.asmae.acceleo.form.radio;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>option</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link mosig.asmae.acceleo.form.impl.optionImpl#getLesOptions <em>Les Options</em>}</li>
 * </ul>
 *
 * @generated
 */
public class optionImpl extends KindImpl implements option
{
  /**
   * The cached value of the '{@link #getLesOptions() <em>Les Options</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLesOptions()
   * @generated
   * @ordered
   */
  protected EList<radio> lesOptions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected optionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FormPackage.Literals.OPTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<radio> getLesOptions()
  {
    if (lesOptions == null)
    {
      lesOptions = new EObjectContainmentEList<radio>(radio.class, this, FormPackage.OPTION__LES_OPTIONS);
    }
    return lesOptions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FormPackage.OPTION__LES_OPTIONS:
        return ((InternalEList<?>)getLesOptions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FormPackage.OPTION__LES_OPTIONS:
        return getLesOptions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FormPackage.OPTION__LES_OPTIONS:
        getLesOptions().clear();
        getLesOptions().addAll((Collection<? extends radio>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FormPackage.OPTION__LES_OPTIONS:
        getLesOptions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FormPackage.OPTION__LES_OPTIONS:
        return lesOptions != null && !lesOptions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //optionImpl
