/**
 * generated by Xtext 2.25.0
 */
package asmae.form.form;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link asmae.form.form.Model#getName <em>Name</em>}</li>
 *   <li>{@link asmae.form.form.Model#getLesQuestions <em>Les Questions</em>}</li>
 * </ul>
 *
 * @see asmae.form.form.FormPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see asmae.form.form.FormPackage#getModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link asmae.form.form.Model#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Les Questions</b></em>' containment reference list.
   * The list contents are of type {@link asmae.form.form.Question}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Les Questions</em>' containment reference list.
   * @see asmae.form.form.FormPackage#getModel_LesQuestions()
   * @model containment="true"
   * @generated
   */
  EList<Question> getLesQuestions();

} // Model
