/*
 * generated by Xtext 2.25.0
 */
package org.mosig.mde.graphdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GraphAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/mosig/mde/graphdsl/parser/antlr/internal/InternalGraph.tokens");
	}
}
