/*
 * generated by Xtext 2.25.0
 */
package org.mosig.mde.graphdsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.mosig.mde.graphdsl.parser.antlr.internal.InternalGraphParser;
import org.mosig.mde.graphdsl.services.GraphGrammarAccess;

public class GraphParser extends AbstractAntlrParser {

	@Inject
	private GraphGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGraphParser createParser(XtextTokenStream stream) {
		return new InternalGraphParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Graph";
	}

	public GraphGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GraphGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
