/*
 * generated by Xtext 2.25.0
 */
package mosig.asmae.acceleo.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import mosig.asmae.acceleo.FormRuntimeModule;
import mosig.asmae.acceleo.FormStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FormIdeSetup extends FormStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FormRuntimeModule(), new FormIdeModule()));
	}
	
}
