/*
 * generated by Xtext 2.25.0
 */
package xtext.tutorial.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtext.tutorial.ui.internal.TutorialActivator;

public class AIRUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TutorialActivator.getInstance().getInjector("xtext.tutorial.AIR");
	}

}
