/*
 * generated by Xtext 2.25.0
 */
package org.xtext.domainmodel.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDomainmodelScopeProvider extends DelegatingScopeProvider {
}
