/*
 * generated by Xtext 2.25.0
 */
package asmae.ocl.family.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractFamilyValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(asmae.ocl.family.family.FamilyPackage.eINSTANCE);
		return result;
	}
}
