/**
 * generated by Xtext 2.25.0
 */
package org.mosig.mde.graphdsl.graph;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Graph</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mosig.mde.graphdsl.graph.Graph#getTheNodes <em>The Nodes</em>}</li>
 * </ul>
 *
 * @see org.mosig.mde.graphdsl.graph.GraphPackage#getGraph()
 * @model
 * @generated
 */
public interface Graph extends EObject
{
  /**
	 * Returns the value of the '<em><b>The Nodes</b></em>' containment reference list.
	 * The list contents are of type {@link org.mosig.mde.graphdsl.graph.Node}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>The Nodes</em>' containment reference list.
	 * @see org.mosig.mde.graphdsl.graph.GraphPackage#getGraph_TheNodes()
	 * @model containment="true"
	 * @generated
	 */
  EList<Node> getTheNodes();

} // Graph
