/**
 * generated by Xtext 2.25.0
 */
package org.mosig.mde.graphdsl.graph;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.mosig.mde.graphdsl.graph.GraphFactory
 * @model kind="package"
 *        annotation="http://www.eclipse.org/emf/2002/Ecore invocationDelegates='http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot' settingDelegates='http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot' validationDelegates='http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot'"
 * @generated
 */
public interface GraphPackage extends EPackage
{
  /**
	 * The package name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNAME = "graph";

  /**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_URI = "http://www.mosig.org/mde/graphdsl/Graph";

  /**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_PREFIX = "graph";

  /**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  GraphPackage eINSTANCE = org.mosig.mde.graphdsl.graph.impl.GraphPackageImpl.init();

  /**
	 * The meta object id for the '{@link org.mosig.mde.graphdsl.graph.impl.GraphImpl <em>Graph</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.mosig.mde.graphdsl.graph.impl.GraphImpl
	 * @see org.mosig.mde.graphdsl.graph.impl.GraphPackageImpl#getGraph()
	 * @generated
	 */
  int GRAPH = 0;

  /**
	 * The feature id for the '<em><b>The Nodes</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int GRAPH__THE_NODES = 0;

  /**
	 * The number of structural features of the '<em>Graph</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int GRAPH_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link org.mosig.mde.graphdsl.graph.impl.NodeImpl <em>Node</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.mosig.mde.graphdsl.graph.impl.NodeImpl
	 * @see org.mosig.mde.graphdsl.graph.impl.GraphPackageImpl#getNode()
	 * @generated
	 */
  int NODE = 1;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int NODE__NAME = 0;

  /**
	 * The feature id for the '<em><b>Next</b></em>' reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int NODE__NEXT = 1;

  /**
	 * The number of structural features of the '<em>Node</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int NODE_FEATURE_COUNT = 2;


  /**
	 * Returns the meta object for class '{@link org.mosig.mde.graphdsl.graph.Graph <em>Graph</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Graph</em>'.
	 * @see org.mosig.mde.graphdsl.graph.Graph
	 * @generated
	 */
  EClass getGraph();

  /**
	 * Returns the meta object for the containment reference list '{@link org.mosig.mde.graphdsl.graph.Graph#getTheNodes <em>The Nodes</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>The Nodes</em>'.
	 * @see org.mosig.mde.graphdsl.graph.Graph#getTheNodes()
	 * @see #getGraph()
	 * @generated
	 */
  EReference getGraph_TheNodes();

  /**
	 * Returns the meta object for class '{@link org.mosig.mde.graphdsl.graph.Node <em>Node</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Node</em>'.
	 * @see org.mosig.mde.graphdsl.graph.Node
	 * @generated
	 */
  EClass getNode();

  /**
	 * Returns the meta object for the attribute '{@link org.mosig.mde.graphdsl.graph.Node#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.mosig.mde.graphdsl.graph.Node#getName()
	 * @see #getNode()
	 * @generated
	 */
  EAttribute getNode_Name();

  /**
	 * Returns the meta object for the reference list '{@link org.mosig.mde.graphdsl.graph.Node#getNext <em>Next</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the reference list '<em>Next</em>'.
	 * @see org.mosig.mde.graphdsl.graph.Node#getNext()
	 * @see #getNode()
	 * @generated
	 */
  EReference getNode_Next();

  /**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
  GraphFactory getGraphFactory();

  /**
	 * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
	 * @generated
	 */
  interface Literals
  {
    /**
		 * The meta object literal for the '{@link org.mosig.mde.graphdsl.graph.impl.GraphImpl <em>Graph</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.mosig.mde.graphdsl.graph.impl.GraphImpl
		 * @see org.mosig.mde.graphdsl.graph.impl.GraphPackageImpl#getGraph()
		 * @generated
		 */
    EClass GRAPH = eINSTANCE.getGraph();

    /**
		 * The meta object literal for the '<em><b>The Nodes</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference GRAPH__THE_NODES = eINSTANCE.getGraph_TheNodes();

    /**
		 * The meta object literal for the '{@link org.mosig.mde.graphdsl.graph.impl.NodeImpl <em>Node</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.mosig.mde.graphdsl.graph.impl.NodeImpl
		 * @see org.mosig.mde.graphdsl.graph.impl.GraphPackageImpl#getNode()
		 * @generated
		 */
    EClass NODE = eINSTANCE.getNode();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute NODE__NAME = eINSTANCE.getNode_Name();

    /**
		 * The meta object literal for the '<em><b>Next</b></em>' reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference NODE__NEXT = eINSTANCE.getNode_Next();

  }

} //GraphPackage
