/**
 * generated by Xtext 2.25.0
 */
package org.mosig.mde.graphdsl.graph;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mosig.mde.graphdsl.graph.Node#getName <em>Name</em>}</li>
 *   <li>{@link org.mosig.mde.graphdsl.graph.Node#getNext <em>Next</em>}</li>
 * </ul>
 *
 * @see org.mosig.mde.graphdsl.graph.GraphPackage#getNode()
 * @model annotation="http://www.eclipse.org/emf/2002/Ecore constraints='UniqueNode Next'"
 *        annotation="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot UniqueNode='Node.allInstances()-&gt;forAll(n | n &lt;&gt; self implies n.name &lt;&gt; self.name)' Next='self.next -&gt; forAll(n | self.next-&gt;select(m | m = n)-&gt;size()=1)'"
 * @generated
 */
public interface Node extends EObject
{
  /**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.mosig.mde.graphdsl.graph.GraphPackage#getNode_Name()
	 * @model
	 * @generated
	 */
  String getName();

  /**
	 * Sets the value of the '{@link org.mosig.mde.graphdsl.graph.Node#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
  void setName(String value);

  /**
	 * Returns the value of the '<em><b>Next</b></em>' reference list.
	 * The list contents are of type {@link org.mosig.mde.graphdsl.graph.Node}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Next</em>' reference list.
	 * @see org.mosig.mde.graphdsl.graph.GraphPackage#getNode_Next()
	 * @model
	 * @generated
	 */
  EList<Node> getNext();

} // Node
