/*
 * generated by Xtext 2.25.0
 */
package mosig.asmae.acceleo.ui;

import com.google.inject.Injector;
import mosig.asmae.form.ui.internal.FormActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FormExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(FormActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		FormActivator activator = FormActivator.getInstance();
		return activator != null ? activator.getInjector(FormActivator.MOSIG_ASMAE_ACCELEO_FORM) : null;
	}

}
