/*
 * generated by Xtext 2.25.0
 */
package asmae.form.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFormScopeProvider extends DelegatingScopeProvider {
}
