/**
 * generated by Xtext 2.25.0
 */
package mosig.asmae.acceleo.form;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see mosig.asmae.acceleo.form.FormFactory
 * @model kind="package"
 * @generated
 */
public interface FormPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "form";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.asmae.mosig/acceleo/Form";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "form";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FormPackage eINSTANCE = mosig.asmae.acceleo.form.impl.FormPackageImpl.init();

  /**
   * The meta object id for the '{@link mosig.asmae.acceleo.form.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mosig.asmae.acceleo.form.impl.ModelImpl
   * @see mosig.asmae.acceleo.form.impl.FormPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Les Questions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__LES_QUESTIONS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link mosig.asmae.acceleo.form.impl.QuestionImpl <em>Question</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mosig.asmae.acceleo.form.impl.QuestionImpl
   * @see mosig.asmae.acceleo.form.impl.FormPackageImpl#getQuestion()
   * @generated
   */
  int QUESTION = 1;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__LABEL = 0;

  /**
   * The feature id for the '<em><b>Kind Of</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__KIND_OF = 1;

  /**
   * The number of structural features of the '<em>Question</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link mosig.asmae.acceleo.form.impl.KindImpl <em>Kind</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mosig.asmae.acceleo.form.impl.KindImpl
   * @see mosig.asmae.acceleo.form.impl.FormPackageImpl#getKind()
   * @generated
   */
  int KIND = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KIND__NAME = 0;

  /**
   * The number of structural features of the '<em>Kind</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KIND_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mosig.asmae.acceleo.form.impl.inputImpl <em>input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mosig.asmae.acceleo.form.impl.inputImpl
   * @see mosig.asmae.acceleo.form.impl.FormPackageImpl#getinput()
   * @generated
   */
  int INPUT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__NAME = KIND__NAME;

  /**
   * The number of structural features of the '<em>input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_FEATURE_COUNT = KIND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link mosig.asmae.acceleo.form.impl.choiceImpl <em>choice</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mosig.asmae.acceleo.form.impl.choiceImpl
   * @see mosig.asmae.acceleo.form.impl.FormPackageImpl#getchoice()
   * @generated
   */
  int CHOICE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE__NAME = KIND__NAME;

  /**
   * The feature id for the '<em><b>Les Choix</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE__LES_CHOIX = KIND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>choice</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_FEATURE_COUNT = KIND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link mosig.asmae.acceleo.form.impl.checkImpl <em>check</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mosig.asmae.acceleo.form.impl.checkImpl
   * @see mosig.asmae.acceleo.form.impl.FormPackageImpl#getcheck()
   * @generated
   */
  int CHECK = 5;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__LABEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__NAME = 1;

  /**
   * The number of structural features of the '<em>check</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link mosig.asmae.acceleo.form.impl.optionImpl <em>option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mosig.asmae.acceleo.form.impl.optionImpl
   * @see mosig.asmae.acceleo.form.impl.FormPackageImpl#getoption()
   * @generated
   */
  int OPTION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION__NAME = KIND__NAME;

  /**
   * The feature id for the '<em><b>Les Options</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION__LES_OPTIONS = KIND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_FEATURE_COUNT = KIND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link mosig.asmae.acceleo.form.impl.radioImpl <em>radio</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mosig.asmae.acceleo.form.impl.radioImpl
   * @see mosig.asmae.acceleo.form.impl.FormPackageImpl#getradio()
   * @generated
   */
  int RADIO = 7;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RADIO__LABEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RADIO__NAME = 1;

  /**
   * The number of structural features of the '<em>radio</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RADIO_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link mosig.asmae.acceleo.form.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see mosig.asmae.acceleo.form.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link mosig.asmae.acceleo.form.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mosig.asmae.acceleo.form.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link mosig.asmae.acceleo.form.Model#getLesQuestions <em>Les Questions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Les Questions</em>'.
   * @see mosig.asmae.acceleo.form.Model#getLesQuestions()
   * @see #getModel()
   * @generated
   */
  EReference getModel_LesQuestions();

  /**
   * Returns the meta object for class '{@link mosig.asmae.acceleo.form.Question <em>Question</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Question</em>'.
   * @see mosig.asmae.acceleo.form.Question
   * @generated
   */
  EClass getQuestion();

  /**
   * Returns the meta object for the attribute '{@link mosig.asmae.acceleo.form.Question#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see mosig.asmae.acceleo.form.Question#getLabel()
   * @see #getQuestion()
   * @generated
   */
  EAttribute getQuestion_Label();

  /**
   * Returns the meta object for the containment reference '{@link mosig.asmae.acceleo.form.Question#getKindOf <em>Kind Of</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Kind Of</em>'.
   * @see mosig.asmae.acceleo.form.Question#getKindOf()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_KindOf();

  /**
   * Returns the meta object for class '{@link mosig.asmae.acceleo.form.Kind <em>Kind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Kind</em>'.
   * @see mosig.asmae.acceleo.form.Kind
   * @generated
   */
  EClass getKind();

  /**
   * Returns the meta object for the attribute '{@link mosig.asmae.acceleo.form.Kind#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mosig.asmae.acceleo.form.Kind#getName()
   * @see #getKind()
   * @generated
   */
  EAttribute getKind_Name();

  /**
   * Returns the meta object for class '{@link mosig.asmae.acceleo.form.input <em>input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>input</em>'.
   * @see mosig.asmae.acceleo.form.input
   * @generated
   */
  EClass getinput();

  /**
   * Returns the meta object for class '{@link mosig.asmae.acceleo.form.choice <em>choice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>choice</em>'.
   * @see mosig.asmae.acceleo.form.choice
   * @generated
   */
  EClass getchoice();

  /**
   * Returns the meta object for the containment reference list '{@link mosig.asmae.acceleo.form.choice#getLesChoix <em>Les Choix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Les Choix</em>'.
   * @see mosig.asmae.acceleo.form.choice#getLesChoix()
   * @see #getchoice()
   * @generated
   */
  EReference getchoice_LesChoix();

  /**
   * Returns the meta object for class '{@link mosig.asmae.acceleo.form.check <em>check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>check</em>'.
   * @see mosig.asmae.acceleo.form.check
   * @generated
   */
  EClass getcheck();

  /**
   * Returns the meta object for the attribute '{@link mosig.asmae.acceleo.form.check#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see mosig.asmae.acceleo.form.check#getLabel()
   * @see #getcheck()
   * @generated
   */
  EAttribute getcheck_Label();

  /**
   * Returns the meta object for the attribute '{@link mosig.asmae.acceleo.form.check#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mosig.asmae.acceleo.form.check#getName()
   * @see #getcheck()
   * @generated
   */
  EAttribute getcheck_Name();

  /**
   * Returns the meta object for class '{@link mosig.asmae.acceleo.form.option <em>option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>option</em>'.
   * @see mosig.asmae.acceleo.form.option
   * @generated
   */
  EClass getoption();

  /**
   * Returns the meta object for the containment reference list '{@link mosig.asmae.acceleo.form.option#getLesOptions <em>Les Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Les Options</em>'.
   * @see mosig.asmae.acceleo.form.option#getLesOptions()
   * @see #getoption()
   * @generated
   */
  EReference getoption_LesOptions();

  /**
   * Returns the meta object for class '{@link mosig.asmae.acceleo.form.radio <em>radio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>radio</em>'.
   * @see mosig.asmae.acceleo.form.radio
   * @generated
   */
  EClass getradio();

  /**
   * Returns the meta object for the attribute '{@link mosig.asmae.acceleo.form.radio#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see mosig.asmae.acceleo.form.radio#getLabel()
   * @see #getradio()
   * @generated
   */
  EAttribute getradio_Label();

  /**
   * Returns the meta object for the attribute '{@link mosig.asmae.acceleo.form.radio#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mosig.asmae.acceleo.form.radio#getName()
   * @see #getradio()
   * @generated
   */
  EAttribute getradio_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  FormFactory getFormFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link mosig.asmae.acceleo.form.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mosig.asmae.acceleo.form.impl.ModelImpl
     * @see mosig.asmae.acceleo.form.impl.FormPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Les Questions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__LES_QUESTIONS = eINSTANCE.getModel_LesQuestions();

    /**
     * The meta object literal for the '{@link mosig.asmae.acceleo.form.impl.QuestionImpl <em>Question</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mosig.asmae.acceleo.form.impl.QuestionImpl
     * @see mosig.asmae.acceleo.form.impl.FormPackageImpl#getQuestion()
     * @generated
     */
    EClass QUESTION = eINSTANCE.getQuestion();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUESTION__LABEL = eINSTANCE.getQuestion_Label();

    /**
     * The meta object literal for the '<em><b>Kind Of</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__KIND_OF = eINSTANCE.getQuestion_KindOf();

    /**
     * The meta object literal for the '{@link mosig.asmae.acceleo.form.impl.KindImpl <em>Kind</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mosig.asmae.acceleo.form.impl.KindImpl
     * @see mosig.asmae.acceleo.form.impl.FormPackageImpl#getKind()
     * @generated
     */
    EClass KIND = eINSTANCE.getKind();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute KIND__NAME = eINSTANCE.getKind_Name();

    /**
     * The meta object literal for the '{@link mosig.asmae.acceleo.form.impl.inputImpl <em>input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mosig.asmae.acceleo.form.impl.inputImpl
     * @see mosig.asmae.acceleo.form.impl.FormPackageImpl#getinput()
     * @generated
     */
    EClass INPUT = eINSTANCE.getinput();

    /**
     * The meta object literal for the '{@link mosig.asmae.acceleo.form.impl.choiceImpl <em>choice</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mosig.asmae.acceleo.form.impl.choiceImpl
     * @see mosig.asmae.acceleo.form.impl.FormPackageImpl#getchoice()
     * @generated
     */
    EClass CHOICE = eINSTANCE.getchoice();

    /**
     * The meta object literal for the '<em><b>Les Choix</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOICE__LES_CHOIX = eINSTANCE.getchoice_LesChoix();

    /**
     * The meta object literal for the '{@link mosig.asmae.acceleo.form.impl.checkImpl <em>check</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mosig.asmae.acceleo.form.impl.checkImpl
     * @see mosig.asmae.acceleo.form.impl.FormPackageImpl#getcheck()
     * @generated
     */
    EClass CHECK = eINSTANCE.getcheck();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECK__LABEL = eINSTANCE.getcheck_Label();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECK__NAME = eINSTANCE.getcheck_Name();

    /**
     * The meta object literal for the '{@link mosig.asmae.acceleo.form.impl.optionImpl <em>option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mosig.asmae.acceleo.form.impl.optionImpl
     * @see mosig.asmae.acceleo.form.impl.FormPackageImpl#getoption()
     * @generated
     */
    EClass OPTION = eINSTANCE.getoption();

    /**
     * The meta object literal for the '<em><b>Les Options</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPTION__LES_OPTIONS = eINSTANCE.getoption_LesOptions();

    /**
     * The meta object literal for the '{@link mosig.asmae.acceleo.form.impl.radioImpl <em>radio</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mosig.asmae.acceleo.form.impl.radioImpl
     * @see mosig.asmae.acceleo.form.impl.FormPackageImpl#getradio()
     * @generated
     */
    EClass RADIO = eINSTANCE.getradio();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RADIO__LABEL = eINSTANCE.getradio_Label();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RADIO__NAME = eINSTANCE.getradio_Name();

  }

} //FormPackage
