/**
 * generated by Xtext 2.25.0
 */
package mosig.asmae.acceleo.form;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>input</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mosig.asmae.acceleo.form.FormPackage#getinput()
 * @model
 * @generated
 */
public interface input extends Kind
{
} // input
