/**
 * generated by Xtext 2.25.0
 */
package mosig.asmae.acceleo.form;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Kind</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mosig.asmae.acceleo.form.Kind#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see mosig.asmae.acceleo.form.FormPackage#getKind()
 * @model
 * @generated
 */
public interface Kind extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see mosig.asmae.acceleo.form.FormPackage#getKind_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link mosig.asmae.acceleo.form.Kind#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Kind
