/**
 * generated by Xtext 2.25.0
 */
package mosig.asmae.acceleo.form;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>option</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mosig.asmae.acceleo.form.option#getLesOptions <em>Les Options</em>}</li>
 * </ul>
 *
 * @see mosig.asmae.acceleo.form.FormPackage#getoption()
 * @model
 * @generated
 */
public interface option extends Kind
{
  /**
   * Returns the value of the '<em><b>Les Options</b></em>' containment reference list.
   * The list contents are of type {@link mosig.asmae.acceleo.form.radio}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Les Options</em>' containment reference list.
   * @see mosig.asmae.acceleo.form.FormPackage#getoption_LesOptions()
   * @model containment="true"
   * @generated
   */
  EList<radio> getLesOptions();

} // option
