/**
 * generated by Xtext 2.25.0
 */
package mosig.asmae.acceleo.form;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Question</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mosig.asmae.acceleo.form.Question#getLabel <em>Label</em>}</li>
 *   <li>{@link mosig.asmae.acceleo.form.Question#getKindOf <em>Kind Of</em>}</li>
 * </ul>
 *
 * @see mosig.asmae.acceleo.form.FormPackage#getQuestion()
 * @model
 * @generated
 */
public interface Question extends EObject
{
  /**
   * Returns the value of the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' attribute.
   * @see #setLabel(String)
   * @see mosig.asmae.acceleo.form.FormPackage#getQuestion_Label()
   * @model
   * @generated
   */
  String getLabel();

  /**
   * Sets the value of the '{@link mosig.asmae.acceleo.form.Question#getLabel <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' attribute.
   * @see #getLabel()
   * @generated
   */
  void setLabel(String value);

  /**
   * Returns the value of the '<em><b>Kind Of</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kind Of</em>' containment reference.
   * @see #setKindOf(Kind)
   * @see mosig.asmae.acceleo.form.FormPackage#getQuestion_KindOf()
   * @model containment="true"
   * @generated
   */
  Kind getKindOf();

  /**
   * Sets the value of the '{@link mosig.asmae.acceleo.form.Question#getKindOf <em>Kind Of</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kind Of</em>' containment reference.
   * @see #getKindOf()
   * @generated
   */
  void setKindOf(Kind value);

} // Question
