/**
 * generated by Xtext 2.25.0
 */
package mosig.asmae.acceleo.form;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>radio</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mosig.asmae.acceleo.form.radio#getLabel <em>Label</em>}</li>
 *   <li>{@link mosig.asmae.acceleo.form.radio#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see mosig.asmae.acceleo.form.FormPackage#getradio()
 * @model
 * @generated
 */
public interface radio extends EObject
{
  /**
   * Returns the value of the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' attribute.
   * @see #setLabel(String)
   * @see mosig.asmae.acceleo.form.FormPackage#getradio_Label()
   * @model
   * @generated
   */
  String getLabel();

  /**
   * Sets the value of the '{@link mosig.asmae.acceleo.form.radio#getLabel <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' attribute.
   * @see #getLabel()
   * @generated
   */
  void setLabel(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see mosig.asmae.acceleo.form.FormPackage#getradio_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link mosig.asmae.acceleo.form.radio#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // radio
