/**
 * generated by Xtext 2.25.0
 */
package xtext.tutorial.aIR;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Plane</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.tutorial.aIR.Plane#getName <em>Name</em>}</li>
 *   <li>{@link xtext.tutorial.aIR.Plane#getPassengers <em>Passengers</em>}</li>
 *   <li>{@link xtext.tutorial.aIR.Plane#getMotorisation <em>Motorisation</em>}</li>
 * </ul>
 *
 * @see xtext.tutorial.aIR.AIRPackage#getPlane()
 * @model
 * @generated
 */
public interface Plane extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xtext.tutorial.aIR.AIRPackage#getPlane_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xtext.tutorial.aIR.Plane#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Passengers</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Passengers</em>' attribute.
   * @see #setPassengers(int)
   * @see xtext.tutorial.aIR.AIRPackage#getPlane_Passengers()
   * @model
   * @generated
   */
  int getPassengers();

  /**
   * Sets the value of the '{@link xtext.tutorial.aIR.Plane#getPassengers <em>Passengers</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Passengers</em>' attribute.
   * @see #getPassengers()
   * @generated
   */
  void setPassengers(int value);

  /**
   * Returns the value of the '<em><b>Motorisation</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.tutorial.aIR.Engines}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Motorisation</em>' attribute.
   * @see xtext.tutorial.aIR.Engines
   * @see #setMotorisation(Engines)
   * @see xtext.tutorial.aIR.AIRPackage#getPlane_Motorisation()
   * @model
   * @generated
   */
  Engines getMotorisation();

  /**
   * Sets the value of the '{@link xtext.tutorial.aIR.Plane#getMotorisation <em>Motorisation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Motorisation</em>' attribute.
   * @see xtext.tutorial.aIR.Engines
   * @see #getMotorisation()
   * @generated
   */
  void setMotorisation(Engines value);

} // Plane
