/*
 * generated by Xtext 2.25.0
 */
package org.mosig.lab4.myfamily.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FamilyUiModule extends AbstractFamilyUiModule {

	public FamilyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
