/*
 * generated by Xtext 2.25.0
 */
package asmae.form.ide;

import asmae.form.FormRuntimeModule;
import asmae.form.FormStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FormIdeSetup extends FormStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FormRuntimeModule(), new FormIdeModule()));
	}
	
}
