/*
 * generated by Xtext 2.25.0
 */
package org.mosig.lab4.myfamily.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.mosig.lab4.myfamily.ide.contentassist.antlr.internal.InternalFamilyParser;
import org.mosig.lab4.myfamily.services.FamilyGrammarAccess;

public class FamilyParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(FamilyGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, FamilyGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getFamilyAccess().getGroup(), "rule__Family__Group__0");
			builder.put(grammarAccess.getFamilyAccess().getGroup_3(), "rule__Family__Group_3__0");
			builder.put(grammarAccess.getFamilyAccess().getGroup_4(), "rule__Family__Group_4__0");
			builder.put(grammarAccess.getFamilyAccess().getGroup_5(), "rule__Family__Group_5__0");
			builder.put(grammarAccess.getFamilyAccess().getGroup_6(), "rule__Family__Group_6__0");
			builder.put(grammarAccess.getModelAccess().getFamiliesAssignment(), "rule__Model__FamiliesAssignment");
			builder.put(grammarAccess.getFamilyAccess().getSurnameAssignment_1(), "rule__Family__SurnameAssignment_1");
			builder.put(grammarAccess.getFamilyAccess().getFAssignment_3_1(), "rule__Family__FAssignment_3_1");
			builder.put(grammarAccess.getFamilyAccess().getMAssignment_4_1(), "rule__Family__MAssignment_4_1");
			builder.put(grammarAccess.getFamilyAccess().getSAssignment_5_1(), "rule__Family__SAssignment_5_1");
			builder.put(grammarAccess.getFamilyAccess().getDAssignment_6_1(), "rule__Family__DAssignment_6_1");
			builder.put(grammarAccess.getMemberAccess().getNameAssignment(), "rule__Member__NameAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private FamilyGrammarAccess grammarAccess;

	@Override
	protected InternalFamilyParser createParser() {
		InternalFamilyParser result = new InternalFamilyParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public FamilyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FamilyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
